name: GH Actions CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Weekly tests at midnight on Sundays run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: {{ "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}" }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  environment-config:
    runs-on: ubuntu-latest
    outputs:
      stable-python-version: {{ "${{ steps.get-python-version.outputs.python-version }}" }}
    steps:
      - uses: actions/checkout@v3

      - id: get-python-version
        uses: MDAnalysis/get-latest-python-version@main
        with:
          last-n-minor-release: 1

  main-tests:
    if: "github.repository == '{{ cookiecutter.github_host_account }}/{{ cookiecutter.repo_name }}'"
    runs-on: {{ '${{ matrix.os }}' }}
    strategy:
        fail-fast: false
        matrix:
          os: [macOS-latest, ubuntu-latest, windows-latest]
          python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3

    - name: Build information
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Install environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          extra-specs: {{ "python=${{ matrix.python-version }}" }}

    - name: Install package
      run: |
        python --version
        python -m pip install . --no-deps

    - name: Python information
      run: |
        which python
        which pip
        pip list
        conda info
        conda list

    - name: Run tests
      run: |
        pytest -n 2 -v --cov={{ cookiecutter.package_name }} --cov-report=xml --color=yes {{ cookiecutter.package_name }}/tests/

    - name: codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml
        name: codecov-{{ '${{ matrix.os }}' }}-py{{ '${{ matrix.python-version }}' }}
        verbose: True


  pylint_check:
    if: "github.repository == '{{ cookiecutter.github_host_account }}/{{ cookiecutter.repo_name }}'"
    needs: environment-config
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: {{ '${{ needs.environment-config.outputs.stable-python-version }}' }}

    - name: Install Pylint
      run: |
        which pip
        which python
        pip install pylint

    - name: Run Pylint
      env:
        PYLINTRC: .pylintrc
      run: |
        pylint {{ cookiecutter.repo_name }}


  pypi_check:
    if: "github.repository == '{{ cookiecutter.github_host_account }}/{{ cookiecutter.repo_name }}'"
    needs: environment-config
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python {{ '${{ needs.environment-config.outputs.stable-python-version }}' }}
      uses: actions/setup-python@v4
      with:
        python-version: {{ '${{ needs.environment-config.outputs.stable-python-version }}' }}

    - name: Install dependencies
      run: |
        pip install setuptools cython numpy twine

    - name: Build package
      run: |
        python setup.py sdist

    - name: Check package build
      run: |
        DISTRIBUTION=$(ls -t1 dist/{{ cookiecutter.package_name }}-*.tar.gz | head -n 1)
        test -n "${DISTRIBUTION}" || { echo "no distribution dist/{{ cookiecutter.package_name }}-*.tar.gz found"; exit 1; }
        echo "twine check $DISTRIBUTION"
        twine check $DISTRIBUTION
